name: Reusable Tests

on:
  workflow_call:
    inputs:
      cache:
        required: true
        type: boolean
      solana_cli_version:
        required: true
        type: string
      node_version:
        required: true
        type: string
      cargo_profile:
        required: true
        type: string
      anchor_binary_name:
        required: true
        type: string
env:
  CACHE: inputs.cache
  SOLANA_CLI_VERSION: ${{ inputs.solana_cli_version }}
  NODE_VERSION: ${{ inputs.node_version }}
  CARGO_PROFILE: ${{ inputs.cargo_profile }}
  ANCHOR_BINARY_NAME: ${{ inputs.anchor_binary_name }}
  CARGO_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    ./target/

jobs:
  test-core:
    name: Core Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: 'echo env.CHACHE ${{ env.CACHE }}'
      - run: "echo CACHE compare ${{ env.CACHE != 'false' }}"



